#!/bin/sh
SRC_DIR=/tmp/inst/share/gensol
SOL_DIR=".";
if [ -n "$1" ]; then
	if [ -d "$1" ]; then
		SOL_DIR="$1";
	else
		echo >&2 "$1 is not a directory";
		exit 1;
	fi
fi
exec lua $SRC_DIR/gensol.lua "$SOL_DIR/"
