#!/bin/sh
PREFIX=/usr/local
echo -n "Install path (default /usr/local):"
read path
if [ -n "$path" ]; then
	mkdir -p "$path";
	PREFIX=$path
fi
echo > gensol "#!/bin/sh"
echo >> gensol "SRC_DIR=$PREFIX/share/gensol"
cat >> gensol << "EOF"
SOL_DIR=".";
if [ -n "$1" ]; then
	if [ -d "$1" ]; then
		SOL_FILE="$1";
	else
		echo >&2 "$1 is not a directory";
		exit 1;
	fi
fi
exec lua $SRC_DIR/gensol.lua "$SOL_DIR/"
EOF
sudo mkdir -p "$PREFIX/bin"
sudo install -m 0755 gensol "$PREFIX/bin/gensol"
sudo mkdir -p "$PREFIX/share/gensol"
sudo install -m 0644 gensol.lua "$PREFIX/share/gensol/gensol.lua"